version: '3.8'

services:
  app:
    build: .
    command: 'yarn start'
    ports:
      - '5000:5000'
    volumes:
      - './package.json:/service/package.json'
      - './src:/service/src'
      - './yarn.lock:/service/yarn.lock'

  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
## -- Uncomment to use port 7482 instead of 5432 (in case of port collision) -- ##
    # ports:
    #   - "7482:5432"
